#include "processor.h"

static Opcode op6502[256] =
{
	/* 00 - 0f */
	{"brk",NO_ARG, 0, NULL},
	{"ora (", BYTE_IND_X, 0, NULL},
	{"kil02", NO_ARG, 0, NULL},
	{"slo (", BYTE_IND_X, 0, NULL},
	{"nop02 ", BYTE_ARG, 0, NULL},
	{"ora ", BYTE_ARG, 0, NULL},
	{"asl ", BYTE_ARG, 0, NULL},
	{"slo ", BYTE_ARG, 0, NULL},
	{"php", NO_ARG, 0, NULL},
	{"ora #", BYTE_ARG, 0, NULL},
	{"asl", NO_ARG, 0, NULL},
	{"anc #", BYTE_ARG, 0, NULL},
	{"nop ", WORD_ARG, 0, NULL},
	{"ora ", WORD_ARG, 0, NULL},
	{"asl ", WORD_ARG, 0, NULL},
	{"slo ", WORD_ARG, 0, NULL},
	/* 10 - 1f */
	{"bpl ", REL_ARG_2, 0, NULL},
	{"ora (", BYTE_IND_Y, 0, NULL},
	{"kil12", NO_ARG, 0, NULL},
	{"slo (", BYTE_IND_Y, 0, NULL},
	{"nop (", BYTE_IND_X, 0, NULL},
	{"ora (", BYTE_IND_X, 0, NULL},
	{"asl (", BYTE_IND_X, 0, NULL},
	{"slo (", BYTE_IND_X, 0, NULL},
	{"clc", NO_ARG, 0, NULL},
	{"ora ", WORD_ARG_Y, 0, NULL},
	{"nop1a", NO_ARG, 0, NULL},
	{"slo ", WORD_ARG_Y, 0, NULL},
	{"nop ", WORD_ARG_X, 0, NULL},
	{"ora ", WORD_ARG_X, 0, NULL},
	{"asl ", WORD_ARG_X, 0, NULL},
	{"slo ,", BYTE_ARG, 0, NULL},
	/* 20 - 2f */
	{"jsr ",WORD_ARG, 0},
	{"and (", BYTE_IND_X, 0, NULL},
	{"kil22", NO_ARG, 0, NULL},
	{"rla (", BYTE_IND_X, 0, NULL},
	{"bit ", BYTE_ARG, 0, NULL},
	{"and ", BYTE_ARG, 0, NULL},
	{"rol ", BYTE_ARG, 0, NULL},
	{"rla ", BYTE_ARG, 0, NULL},
	{"plp", NO_ARG, 0, NULL},
	{"and #", BYTE_ARG, 0, NULL},
	{"rol", NO_ARG, 0, NULL},
	{"anc #", BYTE_ARG, 0, NULL},
	{"bit ", WORD_ARG, 0, NULL},
	{"and ", WORD_ARG, 0, NULL},
	{"rol ", WORD_ARG, 0, NULL},
	{"rla ", WORD_ARG, 0, NULL},
	/* 30 - 3f */
	{"bmi ",REL_ARG_2, 0, NULL},
	{"and (", BYTE_IND_Y, 0, NULL},
	{"kil32", NO_ARG, 0, NULL},
	{"rla (", BYTE_IND_Y, 0, NULL},
	{"nop ", BYTE_ARG_X, 0, NULL},
	{"and ", BYTE_ARG_X, 0, NULL},
	{"rol ", BYTE_ARG_X, 0, NULL},
	{"rla ", BYTE_ARG_X, 0, NULL},
	{"sec", NO_ARG, 0, NULL},
	{"and ", WORD_ARG_Y, 0, NULL},
	{"nop3a", NO_ARG, 0, NULL},
	{"rla ", WORD_ARG_Y, 0, NULL},
	{"nop2 ", WORD_ARG_X, 0, NULL},
	{"and ", WORD_ARG_X, 0, NULL},
	{"rol ", WORD_ARG_X, 0, NULL},
	{"rla ", WORD_ARG_X, 0, NULL},
	/* 40 - 4f */
	{"rti", NO_ARG, 1, NULL},
	{"eor (", BYTE_IND_X, 0, NULL},
	{"kil42", NO_ARG, 0, NULL},
	{"sre (", BYTE_IND_X, 0, NULL},
	{"nop ", BYTE_ARG, 0, NULL},
	{"eor ", BYTE_ARG, 0, NULL},
	{"lsr ", BYTE_ARG, 0, NULL},
	{"sre ", BYTE_ARG, 0, NULL},
	{"pha", NO_ARG, 0, NULL},
	{"eor #", BYTE_ARG, 0, NULL},
	{"lsr", NO_ARG, 0, NULL},
	{"alr #", BYTE_ARG, 0, NULL},
	{"jmp ", WORD_ARG, 1, NULL},
	{"eor ", WORD_ARG, 0, NULL},
	{"lsr ", WORD_ARG, 0, NULL},
	{"sre ", WORD_ARG, 0, NULL},
	/* 50 - 5f */
	{"bvc ", REL_ARG_2, 0, NULL},
	{"eor (", BYTE_IND_Y, 0, NULL},
	{"kil52", NO_ARG, 0, NULL},
	{"sre (", BYTE_IND_Y, 0, NULL},
	{"nop ", BYTE_ARG_X, 0, NULL},
	{"eor ", BYTE_ARG_X, 0, NULL},
	{"lsr ", BYTE_ARG_X, 0, NULL},
	{"sre ", BYTE_ARG_X, 0, NULL},
	{"cli", NO_ARG, 0, NULL},
	{"eor ", WORD_ARG_Y, 0, NULL},
	{"nop5a", NO_ARG, 0, NULL},
	{"sre ", WORD_ARG_Y, 0, NULL},
	{"nop3 ", WORD_ARG_X, 0, NULL},
	{"eor ", WORD_ARG_X, 0, NULL},
	{"lsr ", WORD_ARG_X, 0, NULL},
	{"sre ", WORD_ARG_X, 0, NULL},
	/* 60 - 6f */
	{"rts", NO_ARG, 1, NULL},
	{"adc (", BYTE_IND_X, 0, NULL},
	{"kil62", NO_ARG, 0, NULL},
	{"rra ", BYTE_IND_X, 0, NULL},
	{"nop ", BYTE_ARG, 0, NULL},
	{"adc ", BYTE_ARG, 0, NULL},
	{"ror ", BYTE_ARG, 0, NULL},
	{"rra ", BYTE_ARG, 0, NULL},
	{"pla", NO_ARG, 0, NULL},
	{"adc #", BYTE_ARG, 0, NULL},
	{"ror", NO_ARG, 0, NULL},
	{"arr #", BYTE_ARG, 0, NULL},
	{"jmp (", WORD_ARG_IND, 1, NULL},
	{"eor ", WORD_ARG, 0, NULL},
	{"lsr ", WORD_ARG, 0, NULL},
	{"sre ", WORD_ARG, 0, NULL},
	/* 70 - 7f */
	{"bvs ", REL_ARG_2, 0, NULL},
	{"adc (", BYTE_IND_Y, 0, NULL},
	{"kil72", NO_ARG, 0, NULL},
	{"rra (", BYTE_IND_Y, 0, NULL},
	{"nop ", BYTE_ARG_X, 0, NULL},
	{"adc ", BYTE_ARG_X, 0, NULL},
	{"ror ", BYTE_ARG_X, 0, NULL},
	{"rra ", BYTE_ARG_X, 0, NULL},
	{"sei", NO_ARG, 0, NULL},
	{"adc ", WORD_ARG_Y, 0, NULL},
	{"ror", NO_ARG, 0, NULL},
	{"rra ", WORD_ARG_Y, 0, NULL},
	{"nop4 ", WORD_ARG_X, 0, NULL},
	{"adc ", WORD_ARG_X, 0, NULL},
	{"ror ", WORD_ARG_X, 0, NULL},
	{"rra ", WORD_ARG_X, 0, NULL},
	/* 80 - 8f */
	{"nop #", BYTE_ARG,0, NULL},
	{"sta (", BYTE_IND_X,0, NULL},
	{"nop2 #", BYTE_ARG,0, NULL},
	{"sax (", BYTE_IND_X,0, NULL},
	{"sty ", BYTE_ARG,0, NULL},
	{"sta ", BYTE_ARG,0, NULL},
	{"stx ", BYTE_ARG,0, NULL},
	{"sax ", BYTE_ARG,0, NULL},
	{"dey", NO_ARG,0, NULL},
	{"nop3 #", BYTE_ARG,0, NULL},
	{"txa", NO_ARG,0, NULL},
	{"xaa #", BYTE_ARG,0, NULL},
	{"sty ", WORD_ARG,0, NULL},
	{"sta ", WORD_ARG,0, NULL},
	{"stx ", WORD_ARG,0, NULL},
	{"sax ", WORD_ARG,0, NULL},
	/* 90 - 9f */
	{"bcc ", REL_ARG_2,0, NULL},
	{"sta (", BYTE_IND_Y,0, NULL},
	{"kil92", NO_ARG,0, NULL},
	{"ahx (", BYTE_IND_Y,0, NULL},
	{"sty ", BYTE_ARG_X,0, NULL},
	{"sta ", BYTE_ARG_X,0, NULL},
	{"stx ", BYTE_ARG_Y,0, NULL},
	{"sax ", BYTE_ARG_Y,0, NULL},
	{"tya", NO_ARG,0, NULL},
	{"sta ", WORD_ARG_Y,0, NULL},
	{"txs", NO_ARG,0, NULL},
	{"tas ", WORD_ARG_Y,0, NULL},
	{"shy ", WORD_ARG_X,0, NULL},
	{"sta ", WORD_ARG_X,0, NULL},
	{"shx ", WORD_ARG_Y,0, NULL},
	{"ahx ", WORD_ARG_Y,0, NULL},
	/* a0 - af */
	{"ldy #", BYTE_ARG,0, NULL},
	{"lda (", BYTE_IND_X,0, NULL},
	{"ldx #", BYTE_ARG,0, NULL},
	{"lax (", BYTE_IND_X,0, NULL},
	{"ldy ",  BYTE_ARG,0, NULL},
	{"lda ", BYTE_ARG,0, NULL},
	{"ldx ", BYTE_ARG,0, NULL},
	{"lax ", BYTE_ARG,0, NULL},
	{"tay", NO_ARG,0, NULL},
	{"lda #", BYTE_ARG,0, NULL},
	{"tax", NO_ARG,0, NULL},
	{"lxa #", BYTE_ARG,0, NULL},
	{"ldy ", WORD_ARG,0, NULL},
	{"lda ", WORD_ARG,0, NULL},
	{"ldx ", WORD_ARG,0, NULL},
	{"lax ", WORD_ARG,0, NULL},
	/* b0 - bf */
	{"bcs ", REL_ARG_2,0, NULL},
	{"lda (", BYTE_IND_Y,0, NULL},
	{"kilb2", NO_ARG,0, NULL},
	{"lax (", BYTE_IND_Y,0, NULL},
	{"ldy (", BYTE_IND_X,0, NULL},
	{"lda (", BYTE_IND_X,0, NULL},
	{"ldx (", BYTE_IND_Y,0, NULL},
	{"lax (", BYTE_IND_Y,0, NULL},
	{"clv", NO_ARG,0, NULL},
	{"lda ", WORD_ARG_Y,0, NULL},
	{"tsx", NO_ARG,0, NULL},
	{"las ", WORD_ARG_Y,0, NULL},
	{"ldy ", WORD_ARG_X,0, NULL},
	{"lda ", WORD_ARG_X,0, NULL},
	{"ldx ", WORD_ARG_Y,0, NULL},
	{"lax ", WORD_ARG_Y,0, NULL},
	/* c0 - cf */
	{"cpy #", BYTE_ARG,0, NULL},
	{"cmp (", BYTE_IND_X, 0, NULL},
	{"nop4 #", BYTE_ARG, 0, NULL},
	{"dcp (", BYTE_IND_X, 0, NULL},
	{"cpy ", BYTE_ARG, 0, NULL},
	{"cmp ", BYTE_ARG, 0, NULL},
	{"dec ", BYTE_ARG, 0, NULL},
	{"dcp ", BYTE_ARG, 0, NULL},
	{"iny", NO_ARG, 0, NULL},
	{"cmp #", BYTE_ARG, 0, NULL},
	{"dex", NO_ARG, 0, NULL},
	{"axs #", BYTE_ARG, 0, NULL},
	{"cpy ", WORD_ARG, 0, NULL},
	{"cmp ", WORD_ARG, 0, NULL},
	{"dec ", WORD_ARG, 0, NULL},
	{"dcp ", WORD_ARG, 0, NULL},
	/* d0 - df */
	{"bne ", REL_ARG_2,0, NULL},
	{"cmp (", BYTE_IND_Y, 0, NULL},
	{"kild2", NO_ARG, 0, NULL},
	{"dcp (", BYTE_IND_Y, 0, NULL},
	{"nop2 ", BYTE_ARG_X, 0, NULL},
	{"cmp ", BYTE_ARG_X, 0, NULL},
	{"dec ", BYTE_ARG_X, 0, NULL},
	{"dcp ", BYTE_ARG_X, 0, NULL},
	{"cld", NO_ARG, 0, NULL},
	{"cmp ", WORD_ARG_Y, 0, NULL},
	{"nopda ", NO_ARG, 0, NULL},
	{"dcp ", WORD_ARG_Y, 0, NULL},
	{"nop5 ", WORD_ARG_X, 0, NULL},
	{"cmp ", WORD_ARG_X, 0, NULL},
	{"dec ", WORD_ARG_X, 0, NULL},
	{"dcp ", WORD_ARG_X, 0, NULL},
	/* e0 - ef */
	{"cpx #", BYTE_ARG,0, NULL},
	{"sbc (", BYTE_IND_X, 0, NULL},
	{"nop5 #", BYTE_ARG, 0, NULL},
	{"isc (", BYTE_IND_X, 0, NULL},
	{"cpx ", BYTE_ARG, 0, NULL},
	{"sbc ", BYTE_ARG, 0, NULL},
	{"inc ", BYTE_ARG, 0, NULL},
	{"isc ", BYTE_ARG, 0, NULL},
	{"inx", NO_ARG, 0, NULL},
	{"sbc #", BYTE_ARG, 0, NULL},
	{"nop", NO_ARG, 0, NULL},
	{"sbc2 #", BYTE_ARG, 0, NULL},
	{"cpx ", WORD_ARG, 0, NULL},
	{"sbc ", WORD_ARG, 0, NULL},
	{"inc ", WORD_ARG, 0, NULL},
	{"isc ", WORD_ARG, 0, NULL},
	/* f0 - ff */
	{"beq ", REL_ARG_2,0, NULL},
	{"sbc (", BYTE_IND_Y, 0, NULL},
	{"kilf2", NO_ARG, 0, NULL},
	{"isc (", BYTE_IND_Y, 0, NULL},
	{"nop3 ", BYTE_ARG_X, 0, NULL},
	{"sbc ", BYTE_ARG_X, 0, NULL},
	{"inc ", BYTE_ARG_X, 0, NULL},
	{"isc ", BYTE_ARG_X, 0, NULL},
	{"sed", NO_ARG, 0, NULL},
	{"sbc ", WORD_ARG_Y, 0, NULL},
	{"nopfa",NO_ARG, 0, NULL},
	{"isc ", WORD_ARG_Y, 0, NULL},
	{"nop6 ", WORD_ARG_X, 0, NULL},
	{"sbc ", WORD_ARG_X, 0, NULL},
	{"inc ", WORD_ARG_X, 0, NULL},
	{"isc ", WORD_ARG_X, 0, NULL}	
};

Opcode *get_6502_opcode_by_index(tByte index)
{
	return op6502+index;
}
