#include "processor.h"

static Opcode op8085[256] =
{
	/* 00 - 0f */
	{"nop",NO_ARG, 0, NULL},
	{"lxi b,", WORD_ARG, 0, NULL},
	{"stax b", NO_ARG, 0, NULL},
	{"inx b", NO_ARG, 0, NULL},
	{"inr b", NO_ARG, 0, NULL},
	{"dcr b", NO_ARG, 0, NULL},
	{"mvi b,", BYTE_ARG, 0, NULL},
	{"rlc", NO_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"dad b", NO_ARG, 0, NULL},
	{"ldax b", NO_ARG, 0, NULL},
	{"dcx b", NO_ARG, 0, NULL},
	{"inr c", NO_ARG, 0, NULL},
	{"dcr c", NO_ARG, 0, NULL},
	{"mvi c,", BYTE_ARG, 0, NULL},
	{"rrc", NO_ARG, 0, NULL},
	/* 10 - 1f */
	{"*",NO_ARG, 0, NULL},
	{"lxi d,", WORD_ARG, 0, NULL},
	{"stax d", NO_ARG, 0, NULL},
	{"inx d", NO_ARG, 0, NULL},
	{"inr d", NO_ARG, 0, NULL},
	{"dcr d", NO_ARG, 0, NULL},
	{"mvi d,", BYTE_ARG, 0, NULL},
	{"ral", NO_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"dad d", NO_ARG, 0, NULL},
	{"ldax d", NO_ARG, 0, NULL},
	{"dcx d", NO_ARG, 0, NULL},
	{"inr e", NO_ARG, 0, NULL},
	{"dcr e", NO_ARG, 0, NULL},
	{"mvi e,", BYTE_ARG, 0, NULL},
	{"rar", NO_ARG, 0, NULL},
	/* 20 - 2f */
	{"rim",NO_ARG, 0},
	{"lxi h,", WORD_ARG, 0, NULL},
	{"shld ", WORD_ARG, 0, NULL},
	{"inx h", NO_ARG, 0, NULL},
	{"inr h", NO_ARG, 0, NULL},
	{"dcr h", NO_ARG, 0, NULL},
	{"mvi h,", BYTE_ARG, 0, NULL},
	{"daa", NO_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"dad h", NO_ARG, 0, NULL},
	{"lhld d,", WORD_ARG, 0, NULL},
	{"dcx h", NO_ARG, 0, NULL},
	{"inr l", NO_ARG, 0, NULL},
	{"dcr l", NO_ARG, 0, NULL},
	{"mvi l,", BYTE_ARG, 0, NULL},
	{"cma", NO_ARG, 0, NULL},
	/* 30 - 3f */
	{"sim",NO_ARG, 0, NULL},
	{"lxi sp,", WORD_ARG, 0, NULL},
	{"sta ", WORD_ARG, 0, NULL},
	{"inx sp", NO_ARG, 0, NULL},
	{"inr m", NO_ARG, 0, NULL},
	{"dcr m", NO_ARG, 0, NULL},
	{"mvi m,", BYTE_ARG, 0, NULL},
	{"stc", NO_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"dad sp", NO_ARG, 0, NULL},
	{"lda ", WORD_ARG, 0, NULL},
	{"dcx sp", NO_ARG, 0, NULL},
	{"inr a", NO_ARG, 0, NULL},
	{"dcr a", NO_ARG, 0, NULL},
	{"mvi a,", BYTE_ARG, 0, NULL},
	{"cmc", NO_ARG, 0, NULL},
	/* 40 - 4f */
	{"mov b,b", NO_ARG, 0, NULL},
	{"mov b,c", NO_ARG, 0, NULL},
	{"mov b,d", NO_ARG, 0, NULL},
	{"mov b,e", NO_ARG, 0, NULL},
	{"mov b,h", NO_ARG, 0, NULL},
	{"mov b,l", NO_ARG, 0, NULL},
	{"mov b,m", NO_ARG, 0, NULL},
	{"mov b,a", NO_ARG, 0, NULL},
	{"mov c,b", NO_ARG, 0, NULL},
	{"mov c,c", NO_ARG, 0, NULL},
	{"mov c,d", NO_ARG, 0, NULL},
	{"mov c,e", NO_ARG, 0, NULL},
	{"mov c,h", NO_ARG, 0, NULL},
	{"mov c,l", NO_ARG, 0, NULL},
	{"mov c,m", NO_ARG, 0, NULL},
	{"mov c,a", NO_ARG, 0, NULL},
	/* 50 - 5f */
	{"mov d,b", NO_ARG, 0, NULL},
	{"mov d,c", NO_ARG, 0, NULL},
	{"mov d,d", NO_ARG, 0, NULL},
	{"mov d,e", NO_ARG, 0, NULL},
	{"mov d,h", NO_ARG, 0, NULL},
	{"mov d,l", NO_ARG, 0, NULL},
	{"mov d,m", NO_ARG, 0, NULL},
	{"mov d,a", NO_ARG, 0, NULL},
	{"mov e,b", NO_ARG, 0, NULL},
	{"mov e,c", NO_ARG, 0, NULL},
	{"mov e,d", NO_ARG, 0, NULL},
	{"mov e,e", NO_ARG, 0, NULL},
	{"mov e,h", NO_ARG, 0, NULL},
	{"mov e,l", NO_ARG, 0, NULL},
	{"mov e,m", NO_ARG, 0, NULL},
	{"mov e,a", NO_ARG, 0, NULL},
	/* 60 - 6f */
	{"mov h,b", NO_ARG, 0, NULL},
	{"mov h,c", NO_ARG, 0, NULL},
	{"mov h,d", NO_ARG, 0, NULL},
	{"mov h,e", NO_ARG, 0, NULL},
	{"mov h,h", NO_ARG, 0, NULL},
	{"mov h,l", NO_ARG, 0, NULL},
	{"mov h,m", NO_ARG, 0, NULL},
	{"mov h,a", NO_ARG, 0, NULL},
	{"mov l,b", NO_ARG, 0, NULL},
	{"mov l,c", NO_ARG, 0, NULL},
	{"mov l,d", NO_ARG, 0, NULL},
	{"mov l,e", NO_ARG, 0, NULL},
	{"mov l,h", NO_ARG, 0, NULL},
	{"mov l,l", NO_ARG, 0, NULL},
	{"mov l,m", NO_ARG, 0, NULL},
	{"mov l,a", NO_ARG, 0, NULL},
	/* 70 - 7f */
	{"mov m,b", NO_ARG, 0, NULL},
	{"mov m,c", NO_ARG, 0, NULL},
	{"mov m,d", NO_ARG, 0, NULL},
	{"mov m,e", NO_ARG, 0, NULL},
	{"mov m,h", NO_ARG, 0, NULL},
	{"mov m,l", NO_ARG, 0, NULL},
	{"hlt", NO_ARG, 0, NULL},
	{"mov m,a", NO_ARG, 0, NULL},
	{"mov a,b", NO_ARG, 0, NULL},
	{"mov a,c", NO_ARG, 0, NULL},
	{"mov a,d", NO_ARG, 0, NULL},
	{"mov a,e", NO_ARG, 0, NULL},
	{"mov a,h", NO_ARG, 0, NULL},
	{"mov a,l", NO_ARG, 0, NULL},
	{"mov a,m", NO_ARG, 0, NULL},
	{"mov a,a", NO_ARG, 0, NULL},
	/* 80 - 8f */
	{"add b", NO_ARG,0, NULL},
	{"add c", NO_ARG,0, NULL},
	{"add d", NO_ARG,0, NULL},
	{"add e", NO_ARG,0, NULL},
	{"add h", NO_ARG,0, NULL},
	{"add l", NO_ARG,0, NULL},
	{"add m", NO_ARG,0, NULL},
	{"add a", NO_ARG,0, NULL},
	{"adc b", NO_ARG,0, NULL},
	{"adc c", NO_ARG,0, NULL},
	{"adc d", NO_ARG,0, NULL},
	{"adc e", NO_ARG,0, NULL},
	{"adc h", NO_ARG,0, NULL},
	{"adc l", NO_ARG,0, NULL},
	{"adc m", NO_ARG,0, NULL},
	{"adc a", NO_ARG,0, NULL},
	/* 90 - 9f */
	{"sub b", NO_ARG,0, NULL},
	{"sub c", NO_ARG,0, NULL},
	{"sub d", NO_ARG,0, NULL},
	{"sub e", NO_ARG,0, NULL},
	{"sub h", NO_ARG,0, NULL},
	{"sub l", NO_ARG,0, NULL},
	{"sub m", NO_ARG,0, NULL},
	{"sub a", NO_ARG,0, NULL},
	{"sbb b", NO_ARG,0, NULL},
	{"sbb c", NO_ARG,0, NULL},
	{"sbb d", NO_ARG,0, NULL},
	{"sbb e", NO_ARG,0, NULL},
	{"sbb h", NO_ARG,0, NULL},
	{"sbb l", NO_ARG,0, NULL},
	{"sbb m", NO_ARG,0, NULL},
	{"sbb a", NO_ARG,0, NULL},
	/* a0 - af */
	{"ana b", NO_ARG,0, NULL},
	{"ana c", NO_ARG,0, NULL},
	{"ana d", NO_ARG,0, NULL},
	{"ana e", NO_ARG,0, NULL},
	{"ana h", NO_ARG,0, NULL},
	{"ana l", NO_ARG,0, NULL},
	{"ana m", NO_ARG,0, NULL},
	{"ana a", NO_ARG,0, NULL},
	{"xra b", NO_ARG,0, NULL},
	{"xra c", NO_ARG,0, NULL},
	{"xra d", NO_ARG,0, NULL},
	{"xra e", NO_ARG,0, NULL},
	{"xra h", NO_ARG,0, NULL},
	{"xra l", NO_ARG,0, NULL},
	{"xra m", NO_ARG,0, NULL},
	{"xra a", NO_ARG,0, NULL},
	/* b0 - bf */
	{"ora b", NO_ARG,0, NULL},
	{"ora c", NO_ARG,0, NULL},
	{"ora d", NO_ARG,0, NULL},
	{"ora e", NO_ARG,0, NULL},
	{"ora h", NO_ARG,0, NULL},
	{"ora l", NO_ARG,0, NULL},
	{"ora m", NO_ARG,0, NULL},
	{"ora a", NO_ARG,0, NULL},
	{"cmp b", NO_ARG,0, NULL},
	{"cmp c", NO_ARG,0, NULL},
	{"cmp d", NO_ARG,0, NULL},
	{"cmp e", NO_ARG,0, NULL},
	{"cmp h", NO_ARG,0, NULL},
	{"cmp l", NO_ARG,0, NULL},
	{"cmp m", NO_ARG,0, NULL},
	{"cmp a", NO_ARG,0, NULL},
	/* c0 - cf */
	{"rnz", NO_ARG,0, NULL},
	{"pop b", NO_ARG, 0, NULL},
	{"jnz ", WORD_ARG, 0, NULL},
	{"jmp ", WORD_ARG, 1, NULL},
	{"cnz ", WORD_ARG, 0, NULL},
	{"push b", NO_ARG, 0, NULL},
	{"adi ", BYTE_ARG, 0, NULL},
	{"rst 0", NO_ARG, 0, NULL},
	{"rz", NO_ARG, 0, NULL},
	{"ret", NO_ARG, 1, NULL},
	{"jz ", WORD_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"cz ", WORD_ARG, 0, NULL},
	{"call ", WORD_ARG, 0, NULL},
	{"aci ", BYTE_ARG, 0, NULL},
	{"rst 1", NO_ARG, 0, NULL},
	/* d0 - df */
	{"rnc", NO_ARG,0, NULL},
	{"pop d", NO_ARG, 0, NULL},
	{"jnc ", WORD_ARG, 0, NULL},
	{"out ", BYTE_ARG, 0, NULL},
	{"cnc ", WORD_ARG, 0, NULL},
	{"push d", NO_ARG, 0, NULL},
	{"sui ", BYTE_ARG, 0, NULL},
	{"rst 2", NO_ARG, 0, NULL},
	{"rc", NO_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"jc ", WORD_ARG, 0, NULL},
	{"in ", BYTE_ARG, 0, NULL},
	{"cc ", WORD_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"sbi ", BYTE_ARG, 0, NULL},
	{"rst 3", NO_ARG, 0, NULL},
	/* e0 - ef */
	{"rpo", NO_ARG,0, NULL},
	{"pop h", NO_ARG, 0, NULL},
	{"jpo ", WORD_ARG, 0, NULL},
	{"xthl", NO_ARG, 0, NULL},
	{"cpo ", WORD_ARG, 0, NULL},
	{"push h", NO_ARG, 0, NULL},
	{"ani ", BYTE_ARG, 0, NULL},
	{"rst 4", NO_ARG, 0, NULL},
	{"rpe", NO_ARG, 0, NULL},
	{"pchl", NO_ARG, 0, NULL},
	{"jpe ", WORD_ARG, 0, NULL},
	{"xchg", NO_ARG, 0, NULL},
	{"cpe ", WORD_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"xri ", BYTE_ARG, 0, NULL},
	{"rst 5", NO_ARG, 0, NULL},
	/* f0 - ff */
	{"rp", NO_ARG,0, NULL},
	{"pop psw", NO_ARG, 0, NULL},
	{"jp ", WORD_ARG, 0, NULL},
	{"di", NO_ARG, 0, NULL},
	{"cp ", WORD_ARG, 0, NULL},
	{"push psw", NO_ARG, 0, NULL},
	{"ori ", BYTE_ARG, 0, NULL},
	{"rst 6", NO_ARG, 0, NULL},
	{"rm", NO_ARG, 0, NULL},
	{"sphl", NO_ARG, 0, NULL},
	{"jm ", WORD_ARG, 0, NULL},
	{"ei", NO_ARG, 0, NULL},
	{"cm ", WORD_ARG, 0, NULL},
	{"*", NO_ARG, 0, NULL},
	{"cpi ", BYTE_ARG, 0, NULL},
	{"rst 7", NO_ARG, 0, NULL}	
};

Opcode *get_8085_opcode_by_index(tByte index)
{
	return op8085+index;
}
