#include "processor.h"

static Opcode opf3850[256] =
{
	/* 00 - 0f */
	{"lr a,ku",NO_ARG, 0, "a = k_upper"},
	{"lr a,kl", NO_ARG, 0, "a = k_lower"},
	{"lr a,qu", NO_ARG, 0, "a = q_upper"},
	{"lr a,ql", NO_ARG, 0, "a = q_lower"},
        
	{"lr ku,a", NO_ARG, 0, "k_upper = a"},
	{"lr kl,a", NO_ARG, 0, "k_lower = a"},
	{"lr qu,a,", NO_ARG, 0, "q_upper = a"},
	{"lr ql,a", NO_ARG, 0, "q_lower = a"},
        
	{"lr k,pc1", NO_ARG, 0, "k = pc1"},
	{"lr pc1,k", NO_ARG, 0, "pc1 = k"},
	{"lr a,is", NO_ARG, 0, "a = ISAR"},
	{"lr is,a", NO_ARG, 0, "ISAR = a"},
	{"pk", NO_ARG, 0, "pc1 = pc0; pc0 = q"},
	{"lr pc,q", NO_ARG, 1, "pc0 = q"},
	{"lr q,dc,", NO_ARG, 0, "dc0 = q"},
	{"lr dc,q", NO_ARG, 0, "q = dc0"},
	/* 10 - 1f */
	{"lr dc,h",NO_ARG, 0, "h = dc0"},
	{"lr h,dc", NO_ARG, 0, "dc0 = h"},
	{"sr 1", NO_ARG, 0, "lsr a"},
	{"sl 1", NO_ARG, 0, "asl a"},
	{"sr 4", NO_ARG, 0, "lsr #4,a"},
	{"sl 4", NO_ARG, 0, "lsl #4,a"},
	{"lm", NO_ARG, 0, "a = (dc0)++"},
	{"st", NO_ARG, 0, "(dc0)++ = a"},
	{"com", NO_ARG, 0, "a = a xor $ff"},
	{"lnk", NO_ARG, 0, "a = a + c"},
	{"di", NO_ARG, 0, "disable irq"},
	{"ei", NO_ARG, 0, "enable irq"},
	{"pop", NO_ARG, 1, "pc0 = pc1"},
	{"lr w,j", NO_ARG, 0, "status_w = j"},
	{"lr j,w", NO_ARG, 0, "j = status_w"},
	{"inc", NO_ARG, 0, "a = a+1"},

	/* 20 - 2f */
	{"li ",BYTE_ARG, 0, "lda #%"},
	{"ni ", BYTE_ARG, 0, "and #%"},
	{"oi ", BYTE_ARG, 0, "ora #%"},
	{"xi ", BYTE_ARG, 0, "eor #%"},
	{"ai ", BYTE_ARG, 0, "add #%"},
	{"ci ", BYTE_ARG, 0, "cmp #%"},
	{"in ", BYTE_ARG, 0, "a = port(%)"},
	{"out ", BYTE_ARG, 0, "port(%) = a"},
	{"pi ", BWORD_ARG, 0, "jsr % (pc1 = pc0)"},
	{"jmp ", BWORD_ARG, 1, "pc0 = %; a = \""},
	{"dci ", BWORD_ARG, 0, "dc0 = %"},
	{"nop", NO_ARG, 0, NULL},
	{"xdc", NO_ARG, 0, "dc0 <-> dc1"},
	{"nop0", NO_ARG, 0, "illegal"},
	{"nop1", NO_ARG, 0, "illegal"},
	{"nop2", NO_ARG, 0, "illegal"},
	/* 30 - 3f */
	{"ds 0",NO_ARG, 0, "dec r0"},
	{"ds 1", NO_ARG, 0, "dec r1"},
	{"ds 2", NO_ARG, 0, "dec r2"},
	{"ds 3", NO_ARG, 0, "dec r3"},
	{"ds 4", NO_ARG, 0, "dec r4"},
	{"ds 5", NO_ARG, 0, "dec r5"},
	{"ds 6", NO_ARG, 0, "dec r6"},
	{"ds 7", NO_ARG, 0, "dec r7"},
	{"ds 8", NO_ARG, 0, "dec r8"},
	{"ds 9", NO_ARG, 0, "dec r9"},
	{"ds 10", NO_ARG, 0, "dec r10"},
	{"ds 11", NO_ARG, 0, "dec r11"},
	{"ds s", NO_ARG, 0, "dec (ISAR)"},
	{"ds i", NO_ARG, 0, "dec (ISAR++)"},
	{"ds d", NO_ARG, 0, "dec (ISAR--)"},
	{"nop3", NO_ARG, 0, "illegal"},
	/* 40 - 4f */
	{"lr a,0",NO_ARG, 0, "a = r0"},
	{"lr a,1", NO_ARG, 0, "a = r1"},
	{"lr a,2", NO_ARG, 0, "a = r2"},
    	{"lr a,3", NO_ARG, 0, "a = r3"},
	{"lr a,4", NO_ARG, 0, "a = r4"},
	{"lr a,5", NO_ARG, 0, "a = r5"},
	{"lr a,6", NO_ARG, 0, "a = r6"},
	{"lr a,7", NO_ARG, 0, "a = r7"},
	{"lr a,8", NO_ARG, 0, "a = r8"},
	{"lr a,9", NO_ARG, 0, "a = r9"},
	{"lr a,10", NO_ARG, 0, "a = r10"},
	{"lr a,11", NO_ARG, 0, "a = r11"},
	{"lr a,s", NO_ARG, 0, "a = (ISAR)"},
	{"lr a,i", NO_ARG, 0, "a = (ISAR++)"},
	{"lr a,d", NO_ARG, 0, "a = (ISAR--)"},
	{"nop4", NO_ARG, 0, "illegal"},
	/* 50 - 5f */
	{"lr 0,a",NO_ARG, 0, "r0 = a"},
	{"lr 1,a", NO_ARG, 0, "r1 = a"},
	{"lr 2,a", NO_ARG, 0, "r2 = a"},
    	{"lr 3,a", NO_ARG, 0, "r3 = a"},
	{"lr 4,a", NO_ARG, 0, "r4 = a"},
	{"lr 5,a", NO_ARG, 0, "r5 = a"},
	{"lr 6,a", NO_ARG, 0, "r6 = a"},
	{"lr 7,a", NO_ARG, 0, "r7 = a"},
	{"lr 8,a", NO_ARG, 0, "r8 = a"},
	{"lr 9,a", NO_ARG, 0, "r9 = a"},
	{"lr 10,a", NO_ARG, 0, "r10 = a"},
	{"lr 11,a", NO_ARG, 0, "r11 = a"},
	{"lr s,a", NO_ARG, 0, "(ISAR) = a"},
	{"lr i,a", NO_ARG, 0, "(ISAR++) = a"},
	{"lr d,a", NO_ARG, 0, "(ISAR--) = a"},
	{"nop5", NO_ARG, 0, "illegal"},
	/* 60 - 6f */
	{"lisu 0",NO_ARG, 0,  "ISAR = ISAR & $7 | $0"},
	{"lisu 1", NO_ARG, 0, "ISAR = ISAR & $7 | $1"},
	{"lisu 2", NO_ARG, 0, "ISAR = ISAR & $7 | $2"},
    	{"lisu 3", NO_ARG, 0, "ISAR = ISAR & $7 | $3"},
	{"lisu 4", NO_ARG, 0, "ISAR = ISAR & $7 | $4"},
	{"lisu 5", NO_ARG, 0, "ISAR = ISAR & $7 | $5"},
	{"lisu 6", NO_ARG, 0, "ISAR = ISAR & $7 | $6"},
	{"lisu 7", NO_ARG, 0, "ISAR = ISAR & $7 | $7"},

	{"lisl 0",NO_ARG, 0,  "ISAR = ISAR & $38 | $0"},
	{"lisl 1", NO_ARG, 0, "ISAR = ISAR & $38 | $8"},
	{"lisl 2", NO_ARG, 0, "ISAR = ISAR & $38 | $10"},
    	{"lisl 3", NO_ARG, 0, "ISAR = ISAR & $38 | $18"},
	{"lisl 4", NO_ARG, 0, "ISAR = ISAR & $38 | $20"},
	{"lisl 5", NO_ARG, 0, "ISAR = ISAR & $38 | $28"},
	{"lisl 6", NO_ARG, 0, "ISAR = ISAR & $38 | $30"},
	{"lisl 7", NO_ARG, 0, "ISAR = ISAR & $38 | $38"},
	/* 70 - 7f */
	{"clr",NO_ARG, 0, "lda #0"},
	{"lis 1", NO_ARG, 0, "lda #1"},
	{"lis 2", NO_ARG, 0, "lda #2"},
    	{"lis 3", NO_ARG, 0, "lda #3"},
	{"lis 4", NO_ARG, 0, "lda #4"},
	{"lis 5", NO_ARG, 0, "lda #5"},
	{"lis 6", NO_ARG, 0, "lda #6"},
	{"lis 7", NO_ARG, 0, "lda #7"},
	{"lis 8", NO_ARG, 0, "lda #8"},
	{"lis 9", NO_ARG, 0, "lda #9"},
	{"lis 10", NO_ARG, 0, "lda #$a"},
	{"lis 11", NO_ARG, 0, "lda #$b"},
	{"lis 12", NO_ARG, 0, "lda #$c"},
	{"lis 13", NO_ARG, 0, "lda #$d"},
	{"lis 14", NO_ARG, 0, "lda #$e"},
	{"lis 15", NO_ARG, 0, "lda #$f"},
	/* 80 - 8f */
	{"bt 0,", REL_ARG_1,0, "TMASK | 0 == 0 -> jmp %"},
	{"bp ", REL_ARG_1,0, "bpl %"},
	{"bc ", REL_ARG_1,0, "bcs %"},
	{"bt 3,", REL_ARG_1,0, "TMASK | 3 == 0 -> jmp %"},
	{"bz ", REL_ARG_1,0, "beq %"},
	{"bt 5,", REL_ARG_1,0, "TMASK | 5 == 0 -> jmp %"},
	{"bt 6,", REL_ARG_1,0, "TMASK | 6 == 0 -> jmp %"},
	{"bt 7,", REL_ARG_1,0, "TMASK | 7 == 0 -> jmp %"},
	{"am", NO_ARG,0, "add (dc0++)"},
	{"amd", NO_ARG,0, "add (dc0++) (BCD !)"},
	{"nm", NO_ARG,0, "and (dc0++)"},
	{"om", NO_ARG,0, "ora (dc0++)"},
	{"xm", NO_ARG,0, "eor (dc0++)"},
	{"cm", NO_ARG,0, "cmp (dc0++)"},
	{"adc", NO_ARG,0, "add (dc0),a (signed)"},
	{"bt7 ", REL_ARG_1,0, "ISAR & 7 != 7 -> jmp %"},
	/* 90 - 9f */
	{"br ", REL_ARG_1,0, "jmp %"},
	{"bm ", REL_ARG_1,0, "bmi %"},
	{"bnc ", REL_ARG_1,0, "bcc %"},
	{"bf 3,", REL_ARG_1,0, "FMASK == 3 -> jmp %"},
	{"bnz ", REL_ARG_1,0, "bne %"},
	{"bf 5,", REL_ARG_1,0, "FMASK == 5 -> jmp %"},
	{"bf 6,", REL_ARG_1,0, "FMASK == 6 -> jmp %"},
	{"bf 7,", REL_ARG_1,0, "FMASK == 7 -> jmp %"},

	{"bno ", REL_ARG_1,0, "bvc %"},
	{"bf 9,", NO_ARG,0, "FMASK == 9 -> jmp %"},
	{"bf 10,", NO_ARG,0, "FMASK == 10 -> jmp %"},
	{"bf 11,", NO_ARG,0, "FMASK == 11 -> jmp %"},
	{"bf 12,", NO_ARG,0, "FMASK == 12 -> jmp %"},
	{"bf 13,", NO_ARG,0, "FMASK == 13 -> jmp %"},
	{"bf 14,", NO_ARG,0, "FMASK == 14 -> jmp %"},
	{"bf 15,", NO_ARG,0, "FMASK == 15 -> jmp %"},
	/* a0 - af */
	{"ins 0", NO_ARG,0, "a = (port0)"},
	{"ins 1", NO_ARG,0, "a = (port1)"},
	{"ins 2", NO_ARG,0, "a = (port2)"},
	{"ins 3", NO_ARG,0, "a = (port3)"},
	{"ins 4", NO_ARG,0, "a = (port4)"},
	{"ins 5", NO_ARG,0, "a = (port5)"},
	{"ins 6", NO_ARG,0, "a = (port6)"},
	{"ins 7", NO_ARG,0, "a = (port7)"},
	{"ins 8", NO_ARG,0, "a = (port8)"},
	{"ins 9", NO_ARG,0, "a = (port9)"},
	{"ins 10", NO_ARG,0, "a = (port10)"},
	{"ins 11", NO_ARG,0, "a = (port11)"},
	{"ins 12", NO_ARG,0, "a = (port12)"},
	{"ins 13", NO_ARG,0, "a = (port13)"},
	{"ins 14", NO_ARG,0, "a = (port14)"},
	{"ins 15", NO_ARG,0, "a = (port15)"},
	/* b0 - bf */
	{"outs 0", NO_ARG,0, "(port0) = a"},
	{"outs 1", NO_ARG,0, "(port1) = a"},
	{"outs 2", NO_ARG,0, "(port2) = a"},
	{"outs 3", NO_ARG,0, "(port3) = a"},
	{"outs 4", NO_ARG,0, "(port4) = a"},
	{"outs 5", NO_ARG,0, "(port5) = a"},
	{"outs 6", NO_ARG,0, "(port6) = a"},
	{"outs 7", NO_ARG,0, "(port7) = a"},
	{"outs 8", NO_ARG,0, "(port8) = a"},
	{"outs 9", NO_ARG,0, "(port9) = a"},
	{"outs 10", NO_ARG,0, "(port10) = a"},
	{"outs 11", NO_ARG,0, "(port11) = a"},
	{"outs 12", NO_ARG,0, "(port12) = a"},
	{"outs 13", NO_ARG,0, "(port13) = a"},
	{"outs 14", NO_ARG,0, "(port14) = a"},
	{"outs 15", NO_ARG,0, "(port16) = a"},
	/* c0 - cf */
	{"as 0", NO_ARG,0, "a = a + r0"},
	{"as 1", NO_ARG,0, "a = a + r1"},
	{"as 2", NO_ARG,0, "a = a + r2"},
	{"as 3", NO_ARG,0, "a = a + r3"},
	{"as 4", NO_ARG,0, "a = a + r4"},
	{"as 5", NO_ARG,0, "a = a + r5"},
	{"as 6", NO_ARG,0, "a = a + r6"},
	{"as 7", NO_ARG,0, "a = a + r7"},
	{"as 8", NO_ARG,0, "a = a + r8"},
	{"as 9", NO_ARG,0, "a = a + r9"},
	{"as 10", NO_ARG,0, "a = a + r10"},
	{"as 11", NO_ARG,0, "a = a + r11"},
	{"as s", NO_ARG,0, "a = a + (ISAR)"},
	{"as i", NO_ARG,0, "a = a + (ISAR++)"},
	{"as d", NO_ARG,0, "a = a + (ISAR--)"},
	{"nop6", NO_ARG,0, "illegal"},
	/* d0 - df */
	{"asd 0", NO_ARG,0, "a = a + r0 (BCD !)"},
	{"asd 1", NO_ARG,0, "a = a + r1 (BCD !)"},
	{"asd 2", NO_ARG,0, "a = a + r2 (BCD !)"},
	{"asd 3", NO_ARG,0, "a = a + r3 (BCD !)"},
	{"asd 4", NO_ARG,0, "a = a + r4 (BCD !)"},
	{"asd 5", NO_ARG,0, "a = a + r5 (BCD !)"},
	{"asd 6", NO_ARG,0, "a = a + r6 (BCD !)"},
	{"asd 7", NO_ARG,0, "a = a + r7 (BCD !)"},
	{"asd 8", NO_ARG,0, "a = a + r8 (BCD !)"},
	{"asd 9", NO_ARG,0, "a = a + r9 (BCD !)"},
	{"asd 10", NO_ARG,0, "a = a + r10 (BCD !)"},
	{"asd 11", NO_ARG,0, "a = a + r11 (BCD !)"},
	{"asd s", NO_ARG,0, "a = a + (ISAR) (BCD !)"},
	{"asd i", NO_ARG,0, "a = a + (ISAR++) (BCD !)"},
	{"asd d", NO_ARG,0, "a = a + (ISAR--) (BCD !)"},
	{"nop7", NO_ARG,0, "illegal"},
	/* e0 - ef */
	{"xs 0", NO_ARG,0, "a = a xor r0"},
	{"xs 1", NO_ARG,0, "a = a xor r1"},
	{"xs 2", NO_ARG,0, "a = a xor r2"},
	{"xs 3", NO_ARG,0, "a = a xor r3"},
	{"xs 4", NO_ARG,0, "a = a xor r4"},
	{"xs 5", NO_ARG,0, "a = a xor r5"},
	{"xs 6", NO_ARG,0, "a = a xor r6"},
	{"xs 7", NO_ARG,0, "a = a xor r7"},
	{"xs 8", NO_ARG,0, "a = a xor r8"},
	{"xs 9", NO_ARG,0, "a = a xor r9"},
	{"xs 10", NO_ARG,0, "a = a xor r10"},
	{"xs 11", NO_ARG,0, "a = a xor r11"},
	{"xs s", NO_ARG,0, "a = a xor (ISAR)"},
	{"xs i", NO_ARG,0, "a = a xor (ISAR++)"},
	{"xs d", NO_ARG,0, "a = a xor (ISAR--)"},
	{"nop8", NO_ARG,0, "illegal"},
	/* f0 - ff */
	{"ns 0", NO_ARG,0, "a = a & r0"},
	{"ns 1", NO_ARG,0, "a = a & r1"},
	{"ns 2", NO_ARG,0, "a = a & r2"},
	{"ns 3", NO_ARG,0, "a = a & r3"},
	{"ns 4", NO_ARG,0, "a = a & r4"},
	{"ns 5", NO_ARG,0, "a = a & r5"},
	{"ns 6", NO_ARG,0, "a = a & r6"},
	{"ns 7", NO_ARG,0, "a = a & r7"},
	{"ns 8", NO_ARG,0, "a = a & r8"},
	{"ns 9", NO_ARG,0, "a = a & r9"},
	{"ns 10", NO_ARG,0, "a = a & r10"},
	{"ns 11", NO_ARG,0, "a = a & r11"},
	{"ns s", NO_ARG,0, "a = a & (ISAR)"},
	{"ns i", NO_ARG,0, "a = a & (ISAR++)"},
	{"ns d", NO_ARG,0, "a = a & (ISAR--)"},
	{"nop9", NO_ARG,0, "illegal"},
};

Opcode *get_f3850_opcode_by_index(tByte index)
{
	return opf3850+index;
}
