version: '3.9'

services:
  development:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04 
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./devcontainer.env
    command: sleep infinity
    volumes:
      - ..:/workspace
      - '/dev/bus/usb:/dev/bus/usb'
    devices:
      #- '/dev/bus/usb:/dev/bus/usb'
      - '/sys/bus/usb/devices:/sys/bus/usb/devices'
      - '/sys/devices:/sys/devices'
    privileged : true
 
